#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"



# debug logs
yabai -m config debug_output on

# Create / Manage spaces
sh "$HOME/.bin/wp.sh"
sh "$HOME/.bin/spacer.sh"

#########################################################################
# LAYOUT                                                                #
#########################################################################

yabai -m config                          \
  # Use bspwm like binary splits
  layout            bsp                  \
  # do not equalize size of children and parents
  auto_balance      off                  \
  # make the new split slightly smaller than the parent
  split_ratio       0.4                  \
  # split to right and down
  window_placement  second_child         \
  # floating windows are always on top
  window_topmost    off                  \
  # padding between screen edges and windows
  top_padding       8                    \
  bottom_padding    8                    \
  left_padding      8                    \
  right_padding     8                    \
  # padding between different windows
  window_gap        8                    \
  #########################################################################
  # MOUSE SUPPORT                                                         #
  #########################################################################
  # set mouse interaction modifier key
  mouse_modifier      fn                 \
  # make focus and mouse follow each other
  mouse_follows_focus on                 \
  focus_follows_mouse off                \
  # move and resize windows using mouse
  mouse_action1       move               \
  mouse_action2       resize             \
  mouse_drop_action   swap               \
  #########################################################################
  # WINDOWS APPEARANCE                                                    #
  #########################################################################
  # show shadows for floating windows only
  window_shadow               float      \
  # render all unfocus windows with 90% opacity
  window_opacity on                      \
  active_window_opacity       1.0        \
  normal_window_opacity       0.60       \
  # borders
  window_border               on         \
  window_border_width         2          \
  window_border_radius        11         \
  active_window_border_color  0xffe1e3e4 \
  normal_window_border_color  0xff2a2f38 \
  insert_feedback_color       0xff9dd274

# external bar
if which spacebar >/dev/null; then
  SPACEBAR_HEIGHT=$(spacebar -m config height)
  yabai -m config external_bar all:"$SPACEBAR_HEIGHT":0
fi



# WINDOW RULES
#
#
yabai -m rule --add app="Emacs"       space=s1
yabai -m rule --add app="Code"        space=s2
yabai -m rule --add app="VSCodium"    space=s2
yabai -m rule --add app="Firefox"     space=s3
yabai -m rule --add app="Safari"      space=s4
yabai -m rule --add app="Chromium"    space=s5
yabai -m rule --add app="kitty"       space=s6
yabai -m rule --add app="qutebrowser" space=s7


# Floats
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="The Unarchiver" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off
yabai -m rule --add app="Fantastical Helper" manage=off
yabai -m rule --add app="Photo Booth" manage=off
yabai -m rule --add app="zoom" manage=off
yabai -m rule --add app="Terminal" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Color Picker$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Preview$" manage=off


yabai -m signal --add event=display_added action="~/.bin/load-layout.sh && ~/.bin/spacer.sh"
yabai -m signal --add event=display_removed action="~/.bin/load-layout.sh && ~/.bin/spacer.sh"
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


# Update spaces if needed
sh "$HOME/.bin/spacer.sh"
sh "$HOME/.bin/wp.sh"


echo "yabai configuration loaded.."

